//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMP2084Project1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class artTable
    {
        public int TitleID { get; set; }
        public string Title { get; set; }
        public string Artist { get; set; }
        public string Year { get; set; }
        public Nullable<int> MuseumID { get; set; }
    
        public virtual museumTable museumTable { get; set; }
    }
}
